### PR TITLE
Analysis on alcohol expenses using the new dataset with receipts texts

### PR DESCRIPTION
**Pull request by fgrehm**
This makes use of the new dataset from GH-188 and provides some insights on alcohol expenses found using that dataset. Not sure if @Irio was able to upload the CSV to S3 yet but the link to download the file is provided as a comment there.

Please note that the 7 "bad reimbursements" I found were already reported 🚀

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @fgrehm — once more, thank you for such a valuable contribution.

Before merging it, would you mind looking after two details:

* According to our architecture every dataset used should be generated by any user (if she want to) even if it needs API keys, private stuff etc. So can you add a script to `src/` that handles that (ref. dataset from #188)
* Also we need to have this script and the dataset documented in the `CONTRIBUTING.md`

**Comment by jtemporal** [comment]
@fgrehm and @cuducos anything I can do to help this get merged?

**Comment by fgrehm** [comment]
@jtemporal @cuducos hum... I think this is / was blocked by implementing the supporting code to OCR receipts from toolbox, but I noticed @Irio merged some of my other PRs so not sure how to proceed here and the other PRs I have open around it 🤔

**Comment by willianpaixao** [comment]
Hello @fgrehm, do you have any updates on this PR?

**Comment by cuducos** [comment]
I'm closing this PR since we have [archived the notebooks](https://github.com/okfn-brasil/serenata-de-amor/releases/tag/notebooks).

**Pull request closed without merging**
