### PR TITLE
Fix Rosie instalation via Docker Compose

### PR DESCRIPTION
**Pull request by cuducos**
Not sure why we added the directory `rosie/` to the `setup` script. I
tried it today and it didn't work – removing it, it works. Can anyone else test it please?

### CODE REVIEW

**Comment by cuducos** [comment]
It looks like that without the `rosie/` in the `setup` script it works on the Docker flow, but not in Travis…

**Comment by Irio** [comment]
Tests passing locally. Maybe aren't passing in the CI because they are run from outside Docker?

**Comment by cuducos** [comment]
Yep… should we move to a dockerized CI infra?

**Comment by Irio** [comment]
I think so.

**Comment by cuducos** [comment]
Closed in favor of #343

**Pull request closed without merging**
