### PR TITLE
Update Rosie docs

### PR DESCRIPTION
**Pull request by cuducos**
**What is the purpose of this Pull Request?**

Instructions to run Rosie weren't working – it looks like we had an `ENTRYPOINT` that have been removed at some point, so the docs were outdated.

**What was done to achieve this purpose?**

Updated the docs adding the missing `python rosie.py` to Docker instructions when needed.

**How to test if it really works?**

Copy and paste Docker commands from `CONTRIBUTING.md` and `rosie/README.md` and make sure they work ; )

**Who can help reviewing it?**

@anaschwendler @jtemporal @Irio @cabral

### CODE REVIEW

**Comment by anaschwendler** [comment]
Thanks for updating that @cuducos! 🎉 

I'll test the commands and show the result here:

1. Clone the project, and change to @cuducos branch:
```
$ git clone git@github.com:okfn-brasil/serenata-de-amor.git
$ cd serenata-de-amor
$ git fetch origin
$ git checkout -b cuducos-fix-rosie-docs origin/cuducos-fix-rosie-docs
$ git merge master
```

Then run the 3 commands @cuducos listed on the PR:
```
$ docker-compose run --rm -v /tmp/serenata-data:/tmp rosie python rosie.py run chamber_of_deputies
<details>
➜  serenata-de-amor git:(cuducos-fix-rosie-docs) docker-compose run --rm -v /tmp/serenata-data:/tmp rosie python rosie.py run chamber_of_deputies
2018-04-23 19:54:58,703 - rosie.chamber_of_deputies.adapter - INFO - Updating companies
Downloading 2016-09-03-companies.xz: 100%|##| 4.84M/4.84M [00:08<00:00, 593kb/s]
2018-04-23 19:55:07,569 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2009
2018-04-23 20:06:21,862 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2010
2018-04-23 20:20:31,975 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2011
^_2018-04-23 20:35:23,932 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2012
2018-04-23 20:48:03,715 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2013
2018-04-23 21:00:09,799 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2014
2018-04-23 21:08:22,410 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2015
2018-04-23 21:19:40,596 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2016
2018-04-23 21:29:43,722 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2017
2018-04-23 21:38:04,124 - rosie.chamber_of_deputies.adapter - INFO - Updating reimbursements from 2018
2018-04-23 21:40:04,872 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2017.csv
2018-04-23 21:40:07,167 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2016.csv
2018-04-23 21:40:09,857 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2014.csv
2018-04-23 21:40:12,727 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2015.csv
2018-04-23 21:40:16,254 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2011.csv
2018-04-23 21:40:22,023 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2010.csv
2018-04-23 21:40:28,775 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2012.csv
2018-04-23 21:40:39,039 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2013.csv
2018-04-23 21:40:51,203 - rosie.chamber_of_deputies.adapter - INFO - Loading reimbursements from /tmp/serenata-data/reimbursements-2009.csv
</details>

![image](https://user-images.githubusercontent.com/4131432/39168227-5824a384-4793-11e8-8cd8-f2c79a1b9c64.png)

```
$ docker run --rm -v /tmp/serenata-data:/tmp/serenata-data datasciencebr/rosie python rosie.py test
```

<details>
➜  serenata-de-amor git:(cuducos-fix-rosie-docs) docker run --rm -v /tmp/serenata-data:/tmp/serenata-data datasciencebr/rosie python rosie.py test 
Unable to find image 'datasciencebr/rosie:latest' locally
latest: Pulling from datasciencebr/rosie
c75480ad9aaf: Already exists 
4c8fb45c59ca: Already exists 
f91c03ab4b30: Pull complete 
4c90e7294a72: Pull complete 
a2df1f6a8bd2: Pull complete 
2023c85c5e95: Pull complete 
c4095cd5fe12: Pull complete 
Digest: sha256:924b7d3755e781b703af99f2f22d856ce0d9fc99ea5ba98f934b3f7f812cf36b
Status: Downloaded newer image for datasciencebr/rosie:latest
............................/usr/local/lib/python3.6/site-packages/geopy/point.py:184: UserWarning: A single number has been passed to the Point constructor. This is probably a mistake, because constructing a Point with just a latitude seems senseless. If this is exactly what was meant, then pass the zero longitude explicitly to get rid of this warning.
  UserWarning)
.....................................
----------------------------------------------------------------------
Ran 65 tests in 4.713s

OK
</details>

They seem to be working, that seem to be output, @cuducos, it wasn't suposed to generate a `irregularities.xz` ?

**Comment by cuducos** [comment]
> They seem to be working, that seem to be output, @cuducos, it wasn't suposed to generate a `irregularities.xz` ?

Actually the file is called `suspicions.xz`. What's insite the `serenata-data` listed last in your `ls`? I'm afraid the volume mapping is not obvious. We should change `-v /tmp/serenata-data:/tmp` by `-v /tmp/serenata-data:/tmp/serenata-data` in the run command maybe. @rogeriochaves, can you confirm this was (or was not) your case in #363?

**Comment by cuducos** [comment]
Ok, @anaschwendler and @rogeriochaves, would you mind testing it again? Two changes:

1. Updated the instructions in `CONTRIBUTING.md` with the proper volume mapping (dcc5d49)
2. Updates the instructions in `rosie/README.md` with the proper file name (609a6e7)

If this works as expected I guess we can close #363 when merging thess fixes.

**Comment by anaschwendler** [comment]
[WIP]
I'll let that running here, and when I get back I'll let my answer here :)

```
$ docker-compose run --rm -v /tmp/serenata-data:/tmp/serenata-data rosie python rosie.py run chamber_of_deputies
```

**Comment by cuducos** [comment]
@anaschwendler, can you share more information so we can try to understand what's going on? I suggested [some](https://github.com/okfn-brasil/serenata-de-amor/issues/363#issuecomment-383546565) elsewhere ; )

**Comment by cuducos** [comment]
BTW why is there a `serenata-data` directroy inside another `serenata-data` directory? Is this some remaining from the previous runs (before we fix the volume mapping)?

**Comment by anaschwendler** [comment]
I'll work on it soon, I don't know why is generating another one, but it is :/

**Comment by cuducos** [comment]
So the `/tmp` (and/or `/tmp/serenata-data`) was clean when you ran the last time. Is that what you're saying?

**Comment by rogeriochaves** [comment]
just saw this issue, I'll try to test it today and get back with the results!

**Comment by anaschwendler** [comment]
Hello everyone, sorry for taking so long to answer that!

The thing is I ran the project with 7GB of memory, and it went further more, but still stuck at some point, and it is not generating the `suspicions.xz` file.

But seems to be working, @cuducos what do you think is the best approach to that?

@rogeriochaves could you run it?

**Comment by rogeriochaves** [comment]
hey @cuducos, I belive you confused me with @ricardochaves because of #363 hahaha

anyway, I'm in a new computer, I hadn't anything of serenata installed here. I followed CONTRIBUTING.md and ran just `docker-compose up`, but got some errors:

```
postgres_1  | 2018-04-29 15:16:19.889 UTC [54] ERROR:  relation "chamber_of_deputies_reimbursement" does not exist at character 35
postgres_1  | 2018-04-29 15:16:19.889 UTC [54] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "chamber_of_deputies_reimbursement"
django_1    | Internal Server Error: /dashboard/chamber_of_deputies/reimbursement/
django_1    | Traceback (most recent call last):
django_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
django_1    |     return self.cursor.execute(sql, params)
django_1    |   File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/database_psycopg2.py", line 35, in execute
django_1    |     **kwargs)
django_1    |   File "/usr/local/lib/python3.6/site-packages/newrelic/hooks/database_dbapi2.py", line 25, in execute
django_1    |     *args, **kwargs)
django_1    | psycopg2.ProgrammingError: relation "chamber_of_deputies_reimbursement" does not exist
django_1    | LINE 1: SELECT COUNT(*) AS "__count" FROM "chamber_of_deputies_reimb...
```

Is there anything I need to run before `docker-compose up` to work? If there is, this is not clear by reading the instructions

I also tried to run just jarbas following the instruction on CONTRIBUTING:
```
docker-compose up jarbas
```
but it doesn't work
```
ERROR: No such service: jarbas
```

I'm running the rosie command now `docker-compose run --rm rosie python rosie.py run chamber_of_deputies`, when I get the output I'll post here

**Comment by cuducos** [comment]
> hey @cuducos, I belive you confused me with @ricardochaves because of #363 hahaha

Totaly. Shame on me. :man_facepalming: 

> I also tried to run just jarbas following the instruction on CONTRIBUTING

And you've found a bug :bug: 

It should be `docker-compose up django`, not `jarbas`. Gonna fix it. (Regarding the other errors it's a matter of running the migrations and provisioning; gonna add that to although it's detailed in `jarbas/README.md`).

Sorry for the confusion, mate ; )

**Comment by cuducos** [comment]
> But seems to be working, @cuducos what do you think is the best approach to that?

Well, @anaschwendler … the good part is that there are so many options : )

Let's see…

1. I tend to agree with you that this _seems to be working_, after all this wasn't a change in code, only in docs – so if the documented code triggers the desired execution, it really seems do be working (and that _might_ suffice for this review)
2. Howerve one _might_ want to properly run stuff and check if the desired execution is indeed doing what it is supposed to do; if that's the case, you still have plenty of options:
    1. You still haven't told me how many RAM you have available, so I still don't know if 7GB (AFAIK the last attempt) is your limit; it it isn't, try running it with more RAM
    2. Try running outside Docker (AFAIK it's still documented in `rosie/README.md`)
    3. Create a VM (we still have credit in DO and that wold cost cents for a couple of hours) with more RAM than your computer and test the branch there
    4. Ask friends with more powerful computer to test that
    5. Asign a new reviewer for this PR (eg. @Irio @jtemporal or @cabral for example, or anyone else form the community)
3. In spite of all that I'm trying to :red_circle: **SPOILER ALERT** :red_circle: use [Dask](https://dask.pydata.org/en/latest/) to make Rosie compatible with computer with less RAM than we need nowadays, however I do belive that would be an issue for another PR (this one was supposed to be a simple 4 lines fix in the docs)

I'm just avoiding being the judge of my own PR, so it's up to you ; )

**Pull request merged**
