### PR TITLE
Short analysis on meals paid for kids

### PR DESCRIPTION
**Pull request by fgrehm**
Yet another small analysis that leverages the OCRed data from https://github.com/datasciencebr/serenata-de-amor/issues/188#issuecomment-283495404. This time the idea is to find meals that might have been paid for deputies kids.

### CODE REVIEW

**Comment by cuducos** [comment]
Just a quick note to document that this PR is waiting for [changes from #197](https://github.com/datasciencebr/serenata-de-amor/pull/197#issuecomment-285665930).

**Comment by fgrehm** [comment]
@cuducos @anaschwendler should I open a new PR? looks like it got closed by an unrelated commit 😊

**Comment by cuducos** [comment]
No need. Gonna reopen that (actually it's in my TODO list to reopen all things closed accidentally when bringing Jarbas in).

**Comment by cuducos** [comment]
Hahaha… funny: gonna close that anyway because we romeved the notebooks at all. Soon we'll be with a space o Kaggle or similar for analysis like that ; )

**Pull request closed without merging**
